tryber/sd-010-a-project-delivery-app

- README.md
- back-end/package-lock.json
- back-end/package.json
- back-end/src/api/app.js
- back-end/src/api/server.js
- back-end/src/database/migrations/20211109162427-create-user.js
- back-end/src/database/migrations/20211109162540-create-sale.js
- back-end/src/database/migrations/20211109162552-create-product.js
- back-end/src/database/migrations/20211109162620-create-products-sale.js
- back-end/src/database/models/index.js
- back-end/src/database/models/product.js
- back-end/src/database/models/productsSale.js
- back-end/src/database/models/sale.js
- back-end/src/database/models/user.js
- back-end/src/database/seeders/20211109174234-seed-users.js
- back-end/src/database/seeders/20211109174319-seed-products.js
Implementado sequelize: migrations, seeders, models.
Migrations e seeders funcionando (rodar comando npm run db:reset e verificar no SQL workbench, ou equivalente)
Models também funcionando (rodar comando npm start e acessar os endpoints /users, /products, /sales para verificar)
> Main Group 11 sequelize

- back-end/src/controllers/userController.js
- back-end/src/middlewares/index.js
- back-end/src/middlewares/validateEmail.js
- back-end/src/middlewares/validatePassword.js
- back-end/src/routers/loginRouter.js
- back-end/src/services/userService.js
- back-end/src/utils/errorMap.js
>  Back-end Login Middlewares

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/index.js
- front-end/src/pages/Login.js
- front-end/src/pages/Register.js
- front-end/src/pages/User.js
- front-end/src/redux/store/index.js
configura base do redux, route login
> feat: main-group-16 frontEnd Configs

- back-end/src/api/app.js
- back-end/src/controllers/index.js
- back-end/src/controllers/productController.js
- back-end/src/database/models/products.js
- back-end/src/routers/index.js
- back-end/src/routers/productRouter.js
- back-end/src/services/index.js
- back-end/src/services/productService.js
- back-end/src/utils/errorMap.js
GET: '/products'   => all produtcs.
> [Main group 13] - Get All Products

- back-end/src/api/app.js
- back-end/src/controllers/userController.js
- back-end/src/middlewares/index.js
- back-end/src/middlewares/validateName.js
- back-end/src/middlewares/validatePassword.js
- back-end/src/routers/index.js
- back-end/src/routers/registerRouter.js
- back-end/src/services/userService.js
- back-end/src/utils/errorMap.js
> Maingroup 13  backend register

- back-end/src/api/app.js
- back-end/src/api/auth/encriptation.js
- back-end/src/api/auth/validateToken.js
- back-end/src/api/controllers/index.js
- back-end/src/api/controllers/userController.js
- back-end/src/api/messages/errorMessages.js
- back-end/src/api/services/index.js
- back-end/src/api/services/userService.js
- back-end/src/database/models/products.js
- back-end/src/database/models/sales.js
- back-end/src/database/models/salesproducts.js
- back-end/src/database/models/user.js
- back-end/src/database/seeders/20211109203203-users.js
- back-end/src/database/seeders/20211109204407-products.js
- back-end/src/tests/login.test.js
Aqui serão desenvolvidas as lógicas da rota de login
> Main group 3 back-end login

- back-end/src/database/models/salesproduct.js
- back-end/src/database/models/user.js
- back-end/src/services/delete.js
- back-end/src/services/find.js
- back-end/src/services/index.js
- back-end/src/services/insert.js
- back-end/src/services/lib.js
- back-end/src/services/update.js
> Back end services - main group 4

- back-end/src/database/migrations/20211109210426-create-user.js
- back-end/src/database/migrations/20211109212240-create-sale.js
- back-end/src/database/migrations/20211109212328-create-product.js
- back-end/src/database/migrations/20211111181809-create-sale-product.js
- back-end/src/database/models/product.js
- back-end/src/database/models/sale.js
- back-end/src/database/models/saleproduct.js
- back-end/src/database/models/user.js
- back-end/src/database/seeders/20211111182412-Products.js
- back-end/src/database/seeders/20211111182451-Users.js
- package-lock.json
Create sequelize models and migrations.
> [GROUP 7] Sequelize

- front-end/src/App.js
- front-end/src/pages/Login.jsx
- front-end/src/routesPaths/paths.js
- front-end/src/utils/utils.js
- package-lock.json
- package.json
Usando o conceito de inversão de dependências foi criado um aquivo somente para armazenar as rotas!
Foi realizado a refatoração da função para torna-la genérica, sendo possível usa-la em outros componentes!
> [Group7 routers] refatoração

- back-end/src/api/app.js
- back-end/src/database/migrations/20211109162427-create-user.js
- back-end/src/database/migrations/20211109162540-create-sale.js
- back-end/src/database/migrations/20211109162552-create-product.js
- back-end/src/database/migrations/20211109162620-create-products-sale.js
- back-end/src/database/models/index.js
- back-end/src/database/models/product.js
- back-end/src/database/models/productsSale.js
- back-end/src/database/models/sale.js
- back-end/src/database/models/user.js
- back-end/src/database/schemas/product.js
- back-end/src/database/schemas/productsSale.js
- back-end/src/database/schemas/sale.js
- back-end/src/database/schemas/user.js
- back-end/src/database/seeders/20211109174234-seed-users.js
- back-end/src/database/seeders/20211109174319-seed-products.js
Sequelize melhor alinhado com o db.example.sql e melhor uso da lib como um todo
> Main group 11 [fix] sequelize

- back-end/package-lock.json
- back-end/src/controllers/userController.js
- back-end/src/services/productService.js
- back-end/src/services/userService.js
- front-end/package-lock.json
> [GROUP 13] - Sale EndPoint

- back-end/src/api/app.js
- back-end/src/controllers/index.js
- back-end/src/controllers/productController.js
- back-end/src/controllers/saleController.js
- back-end/src/routers/index.js
- back-end/src/routers/saleRouter.js
- back-end/src/services/index.js
- back-end/src/services/productService.js
- back-end/src/services/saleService.js
> [Group 13] - Refactor BackEnd

- back-end/src/api/app.js
- back-end/src/api/server.js
- front-end/package-lock.json
- front-end/package.json
- front-end/src/components/LoginForm.jsx
- front-end/src/context/Provider.js
> [Maingroup 13] - Socket.io

- back-end/src/database/migrations/20211109191123-create-product.js
- front-end/src/pages/CustomerProducts.jsx
- front-end/src/pages/components/CheckOutButton.jsx
- front-end/src/pages/components/Headers.jsx
- front-end/src/pages/components/LogoutButton.jsx
- front-end/src/pages/components/ProductCard.jsx
- front-end/src/pages/components/ProductsButton.jsx
- front-end/src/pages/components/ProductsCards.jsx
- front-end/src/pages/components/ShopCartCard.jsx
Changed inputs to buttons when required.
Changed some wrong data-testids.
Changed the way value is shown.
Added checkout button.
> [ Main Group 15 ] [ Feat ] [ Front ] [ fixed some problems as listed below ]

- back-end/.gitignore
- back-end/src/api/app.js
> static routes

- back-end/src/api/app.js
- back-end/src/controllers/User/findAllUsers.js
- back-end/src/controllers/User/findByIdUser.js
- back-end/src/controllers/User/index.js
- back-end/src/controllers/User/removeUser.js
- back-end/src/controllers/User/updateUser.js
- back-end/src/middlewares/errorMiddleware.js
- back-end/src/middlewares/index.js
- back-end/src/middlewares/routeNotFound.js
- back-end/src/routes/userRoutes.js
- front-end/package-lock.json
- front-end/package.json
- front-end/src/components/ErrorBackend/index.jsx
- front-end/src/components/FormRegisterUser/index.jsx
- front-end/src/provider/ManagerUsersProvider.js
- front-end/src/services/api.js
> [MAIN GROUP 4] [API] [FEAT] [ENDPOINTS-FOR-USER]

- back-end/src/controllers/saleController.js
- back-end/src/services/saleService.js
> Maingroup 13 dev sale refactor

- back-end/package-lock.json
- front-end/package-lock.json
- front-end/src/App.js
- front-end/src/App.scss
- front-end/src/Routes.jsx
- front-end/src/contexts/auth.js
- front-end/src/index.js
- front-end/src/pages/Auth.jsx
- front-end/src/styles/pages/Auth.module.scss
- package-lock.json
Essa PR é responsável pelos contextos da aplicação. No momento, cria um contexto para autenticação.
> [GRUPO 10] (Front-end) Contexto

- back-end/src/controllers/User/findByEmailUser.js
- back-end/src/controllers/User/index.js
- back-end/src/routes/userRoutes.js
Adiciona o endpoint /user/email para encontrar o usuário pelo email.
> [MAIN GROUP 4] [API] [FEAT] [ENDPOINT FINDBYEMAILUSER] 

- back-end/src/controllers/saleController.js
- back-end/src/routers/saleRouter.js
- back-end/src/services/saleService.js
- back-end/src/utils/errorMap.js
> Maingroup 13 dev get sales by id entity

- back-end/package-lock.json
- back-end/src/api/app.js
- back-end/src/controllers/salesController.js
- back-end/src/database/migrations/20211109212620-create-products.js
- back-end/src/database/migrations/20211109212703-create-sales.js
- back-end/src/database/migrations/20211109212748-create-sales-products.js
- back-end/src/database/models/Product.js
- back-end/src/database/models/Sale.js
- back-end/src/database/models/SaleProduct.js
- back-end/src/database/models/User.js
- back-end/src/middlewares/saleValidations.js
- back-end/src/routers/salesRouter.js
- back-end/src/services/salesService.js
- back-end/src/tests/createSale.test.js
- front-end/package-lock.json
create flow of sale creation route
> Main group 6 backend checkout

- back-end/package-lock.json
- back-end/src/api/app.js
- back-end/src/sockets/index.js
- front-end/package-lock.json
- front-end/src/context/Provider.js
> [GROUP 13] - back socket

- back-end/src/api/app.js
- back-end/src/controllers/saleController.js
- back-end/src/routers/customerRouter.js
- back-end/src/routers/index.js
- back-end/src/routers/sellerRouter.js
- back-end/src/services/saleService.js
- back-end/src/utils/errorMap.js
> :recycle: refactor: changing route paths

- front-end/src/pages/components/Headers.jsx
> [ Main Group 15 ] [ Fix ] [ Sellers Orders ]

- front-end/src/components/RequestCard/index.jsx
- front-end/src/components/RequestCard/styles.module.css
- front-end/src/utils/dataTestIdsMyRequestPage.js
- front-end/src/utils/formatDate.js
- add data-testId no preço do RequestCard
- remove text-style upperCase do status do RequestCard
- troca do '.' do preço por ',' no preço do  RequestCard
- remove o 'R$' do preço do RequestCard
- Altera a data do RequestCard de dd/mm/aa para dd/mm/aaaa
> [Main Group 17] Fix requisito 22 23 24

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/components/OrderDetails/index.jsx
- front-end/src/components/OrderDetails/styles.module.css
- front-end/src/components/RequestCard/styles.module.css
- front-end/src/context/orderDetailsProvider.jsx
- front-end/src/pages/ClientOrderDetailsPage/index.jsx
- front-end/src/pages/ClientOrderDetailsPage/styles.module.css
- front-end/src/pages/MyRequestsPage/styles.module.css
- front-end/src/services/ClientOrderDetailsPage/fetchSale.js
- front-end/src/utils/dataTestIdsMyRequestPage.js
> [Main Group 17] Tela de Detalhes da venda

- front-end/src/components/ButtonPrimary/styles.css
- front-end/src/components/ButtonSecondary/index.jsx
- front-end/src/components/ButtonSecondary/styles.css
- front-end/src/components/ButtonTertiary/index.jsx
- front-end/src/components/ButtonTertiary/styles.css
- front-end/src/components/InputText/index.jsx
- front-end/src/components/InputText/styles.css
- front-end/src/components/Select/index.jsx
- front-end/src/components/Select/styles.css
- front-end/src/pages/AdminManagerUsers/FormRegisterUser/index.jsx
- front-end/src/pages/AdminManagerUsers/FormRegisterUser/styles.css
- front-end/src/pages/AdminManagerUsers/index.jsx
- front-end/src/pages/AdminManagerUsers/styles.css
- front-end/src/utils/capitalizeString.js
Css básico para o formulário da página AdminManagerUsers, bem como a adição de alguns componentes (botão secundário, botão terciário) e refatoração do formulário e dos componentes que o compõem.
> [MAIN GROUP 4] [FRONT] [FEAT] [Css-Styles-FormRegister]

- front-end/src/components/Header/index.jsx
- front-end/src/components/ItemCard/index.jsx
- front-end/src/components/ItemCard/styles.module.css
- front-end/src/components/LoginForm/index.jsx
- front-end/src/components/RegisterForm/index.jsx
- front-end/src/pages/ClientOrderDetailsPage/index.jsx
- front-end/src/pages/ProductPage/index.jsx
- remove do header e da tela de produtos avisos do react ao utilizar o useEffect sem as devidas dependências
- corrige o erro do input do itemCard ao utilizar um input do tipo text com valores numericos
- alguns ajustes no style do itemCard
- remove consoles.log
- refatoração do ItemCard
> [Main group 17] Fix avisos do react ao usar useEffect

- front-end/src/components/OrderDetails/index.jsx
- front-end/src/components/OrderDetails/styles.module.css
- front-end/src/components/RequestCard/index.jsx
- front-end/src/components/RequestCard/styles.module.css
- front-end/src/components/SellerOrderDetails/index.jsx
- front-end/src/components/SellerOrderDetails/styles.module.css
- front-end/src/pages/ClientOrderDetailsPage/styles.module.css
- front-end/src/pages/SellerPage/styles.module.css
- add style no status 'em transito'
- add style nos buttons e status na pagina de detalhe do pedido
- add hover effect no componente  RequestCard
> [Main group 17] styles

- __tests__/end-to-end/11admin_manage_users.test.js
- back-end/src/controllers/userController.js
- back-end/src/routers/registerRouter.js
- back-end/src/services/userService.js
- front-end/src/App.jsx
- front-end/src/components/LoginForm.jsx
- front-end/src/components/header.jsx
- front-end/src/context/Provider.js
- front-end/src/pages/AdminManage.jsx
> [Main group 13] Requisitos 39 à 42

- back-end/src/controllers/User/createUser.js
- back-end/src/controllers/User/createUserAdmin.js
- back-end/src/controllers/User/index.js
- back-end/src/controllers/User/login.js
- back-end/src/routes/userRoutes.js
- back-end/src/services/takeToken.js
- back-end/src/services/tokenPassword.js
- front-end/src/pages/AdminManagerUsers/FormRegisterUser/index.jsx
Mudança dos values dos options do input Select. Os dados estavam incorretos.
> [MAIN GROUP 4] [FRONT] [FIX] [FORM-REGISTERUSER-OPTIONS-VALUES-SELECT] 

- front-end/src/components/Tbody/index.jsx
Resolve o problema do requisito 44. O data-testid estava errado.
> [MAIN GROUP 4] [FRONT] [FIX] [TABLE-REGISTERED-USERS] 
